// Code generated by go-swagger; DO NOT EDIT.

package example

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetConcatOKCode is the HTTP code returned for type GetConcatOK
const GetConcatOKCode int = 200

/*GetConcatOK No problems

swagger:response getConcatOK
*/
type GetConcatOK struct {
}

// NewGetConcatOK creates GetConcatOK with default headers values
func NewGetConcatOK() *GetConcatOK {

	return &GetConcatOK{}
}

// WriteResponse to the client
func (o *GetConcatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetConcatInternalServerErrorCode is the HTTP code returned for type GetConcatInternalServerError
const GetConcatInternalServerErrorCode int = 500

/*GetConcatInternalServerError Problems.

swagger:response getConcatInternalServerError
*/
type GetConcatInternalServerError struct {
}

// NewGetConcatInternalServerError creates GetConcatInternalServerError with default headers values
func NewGetConcatInternalServerError() *GetConcatInternalServerError {

	return &GetConcatInternalServerError{}
}

// WriteResponse to the client
func (o *GetConcatInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
