// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Example Strings API
This API will give access example string functions


    Schemes:
      http
      https
    Host: localhost
    BasePath: /v0
    Version: 0.0.1
    Contact: <rjj.work@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
